/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CreationsAndView;

import RedirectUserType.MainDoctor;
import RedirectUserType.MainPharmacist;
import static java.awt.Color.blue;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JTextPane;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author 91979
 */
public class Inventory extends javax.swing.JFrame {
    private Connection con;
    private PreparedStatement pst;
    private ResultSet rs;
    private String usertype;
    private int id;
    private String username;

    /**
     * Creates new form Inventory
     */
    public Inventory() {
        initComponents();
    }
    public Inventory(int id, String username, String usertype, Connection con, String prNo) {
        initComponents();
        this.id=id;
        this.con=con;
        this.username=username;
        this.usertype=usertype;
        lblPno.setText(prNo);
        lbllogid.setText(Integer.toString(this.id));
        lblusername.setText(username);
        txtDrugCode.requestFocus();
        btnSalesUpdate.setEnabled(false);
        txtDrugName.setEditable(false);
        txtPay.setEditable(false);
        txtBalance.setEditable(false);
        txtTotalCost.setEditable(false);
        btnadd.setEnabled(false);
        drugLoader();
      }
    
    public void drugLoader(){
        try {
            String sql = "Select * from Items";
            txtDrugCode.removeAll();
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            while(rs.next()){
                txtDrugCode.addItem(rs.getString(1));               
                }
        } catch (SQLException ex) {
            Logger.getLogger(ChannelCreation.class.getName()).log(Level.SEVERE, null, ex);
        }
        AutoCompleteDecorator.decorate(txtDrugCode);
    }
   

    public void DrugCheckput(){
        try {
            String d = txtDrugCode.getSelectedItem().toString();
            pst = con.prepareStatement("Select * from items where itemno = ? ");
            pst.setString(1, d);
            rs = pst.executeQuery();
            if(rs.next()==false){
                JOptionPane.showMessageDialog(this, "Drug Not found");
                txtDrugCode.setSelectedItem(-1);
                txtDrugCode.requestFocus();
            }else{
             String dname = rs.getString("itemname");
             txtDrugName.setText(dname.trim());
             txtDrugName.setEditable(false);
             txtQty.requestFocus();
            }
           } catch (SQLException e) {
               JOptionPane.showMessageDialog(this, "Something went wrong Drugs");
        }
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPno = new javax.swing.JLabel();
        txtDrugName = new javax.swing.JTextField();
        btnadd = new javax.swing.JButton();
        btnSalesUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtQty = new javax.swing.JSpinner();
        txtTotalCost = new javax.swing.JTextField();
        txtPay = new javax.swing.JTextField();
        txtBalance = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDrugCode = new javax.swing.JComboBox<>();
        jChkDrugCode = new javax.swing.JCheckBox();
        btnlogout = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbllogid = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbleDrug = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));

        jPanel2.setBackground(new java.awt.Color(0, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 102, 102))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("Prescription ID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 255));
        jLabel2.setText("Drug Code");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 255));
        jLabel3.setText("Drug Name");

        lblPno.setBackground(new java.awt.Color(51, 102, 255));
        lblPno.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblPno.setForeground(new java.awt.Color(0, 102, 255));
        lblPno.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblPno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        txtDrugName.setBackground(new java.awt.Color(102, 255, 204));
        txtDrugName.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDrugName.setForeground(new java.awt.Color(0, 51, 255));

        btnadd.setBackground(new java.awt.Color(0, 102, 255));
        btnadd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnadd.setForeground(new java.awt.Color(102, 255, 204));
        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnSalesUpdate.setBackground(new java.awt.Color(0, 102, 255));
        btnSalesUpdate.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnSalesUpdate.setForeground(new java.awt.Color(102, 255, 204));
        btnSalesUpdate.setText("Sales Update");
        btnSalesUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesUpdateActionPerformed(evt);
            }
        });

        btnClear.setBackground(new java.awt.Color(0, 102, 255));
        btnClear.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(102, 255, 204));
        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 51, 255));
        jLabel9.setText("Qty");

        txtQty.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtQty.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        txtQty.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txtQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQtyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtyFocusLost(evt);
            }
        });
        txtQty.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                txtQtyCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtQtyInputMethodTextChanged(evt);
            }
        });

        txtTotalCost.setBackground(new java.awt.Color(102, 255, 204));
        txtTotalCost.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTotalCost.setForeground(new java.awt.Color(0, 51, 255));
        txtTotalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalCostActionPerformed(evt);
            }
        });

        txtPay.setBackground(new java.awt.Color(102, 255, 204));
        txtPay.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtPay.setForeground(new java.awt.Color(0, 51, 255));
        txtPay.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPayFocusLost(evt);
            }
        });

        txtBalance.setBackground(new java.awt.Color(102, 255, 204));
        txtBalance.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtBalance.setForeground(new java.awt.Color(0, 51, 255));
        txtBalance.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBalanceFocusLost(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("Pay");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("TotalCost");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("Balance");

        txtDrugCode.setBackground(new java.awt.Color(102, 255, 204));
        txtDrugCode.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDrugCode.setForeground(new java.awt.Color(0, 51, 255));
        txtDrugCode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDrugCodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDrugCodeFocusLost(evt);
            }
        });

        jChkDrugCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkDrugCodeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(106, 106, 106)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPno, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDrugCode, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jChkDrugCode)
                                .addGap(180, 180, 180))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(43, 43, 43)
                                .addComponent(txtDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 130, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPay, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalesUpdate))
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jChkDrugCode)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(7, 7, 7)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblPno, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTotalCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(19, 19, 19)
                                    .addComponent(txtDrugCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtDrugName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jLabel9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnadd, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalesUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        btnlogout.setBackground(new java.awt.Color(153, 255, 255));
        btnlogout.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        btnlogout.setForeground(new java.awt.Color(0, 102, 102));
        btnlogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/left.png"))); // NOI18N
        btnlogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlogoutActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Jokerman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("Founded By Kishore R");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Colonna MT", 1, 48)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 255));
        jLabel6.setText("Sales Inventory Page");

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 255));
        jLabel10.setText("log id: ");

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 255));
        jLabel11.setText("User name:");

        lbllogid.setBackground(new java.awt.Color(255, 255, 255));
        lbllogid.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lbllogid.setForeground(new java.awt.Color(102, 255, 255));
        lbllogid.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbllogid.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        lbllogid.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblusername.setBackground(new java.awt.Color(255, 255, 255));
        lblusername.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        lblusername.setForeground(new java.awt.Color(102, 255, 255));
        lblusername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 255)));
        lblusername.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jtbleDrug.setBackground(new java.awt.Color(153, 255, 255));
        jtbleDrug.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jtbleDrug.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtbleDrug.setForeground(new java.awt.Color(0, 51, 255));
        jtbleDrug.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Prescription ID", "Drug Code", "DrugName", "Qty", "Price", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jtbleDrug.setSelectionBackground(new java.awt.Color(255, 204, 204));
        jtbleDrug.setSelectionForeground(new java.awt.Color(0, 0, 255));
        jtbleDrug.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbleDrugMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jtbleDrugMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jtbleDrug);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnlogout)
                                .addGap(131, 131, 131)
                                .addComponent(jLabel6))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(lbllogid, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(170, 170, 170))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnlogout)
                    .addComponent(jLabel6))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbllogid, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblusername, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 274, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        try {
            String d = txtDrugCode.getSelectedItem().toString();
            pst = con.prepareStatement("Select * from items where itemno = ? ");
            pst.setString(1, d);
            rs = pst.executeQuery();
            int fQty = Integer.parseInt(txtQty.getValue().toString());
            while(rs.next()){
                int currentQty = rs.getInt("qty");
                int sellPrice = rs.getInt("sellprice");
                
                if(fQty>currentQty){
                    JOptionPane.showMessageDialog(this, "Available Qty is : "+currentQty);
                    JOptionPane.showMessageDialog(this, "Qty Not Enough");
                    txtQty.requestFocus();
                }else if(0<fQty&&fQty<=currentQty){
                    int total = fQty*sellPrice;
                    DefaultTableModel df = (DefaultTableModel)jtbleDrug.getModel();
                    df.addRow(new Object[]{
                        lblPno.getText(),
                        txtDrugCode.getSelectedItem().toString(),
                        txtDrugName.getText(),
                        txtQty.getValue().toString(),
                        sellPrice,
                        total
                    });
                    int sum=0;
                    for(int i=0;i<jtbleDrug.getRowCount();i++){
                      sum+=Integer.parseInt(jtbleDrug.getValueAt(i, 5).toString());
                    }
                    txtTotalCost.setText(Integer.toString(sum));
                    btnSalesUpdate.setEnabled(true);
                    txtPay.setEditable(true);
                    btnClear.setEnabled(false);
                }else{
                    JOptionPane.showMessageDialog(this, "Available Qty is : "+currentQty);
                    JOptionPane.showMessageDialog(this, "Qty MissMatch");
                    txtQty.requestFocus();
                }
                
            }
            txtPay.requestFocus();
        }catch(SQLException e){
            
        }
    }//GEN-LAST:event_btnaddActionPerformed
    
    public static boolean numCheck(JTextField txt){
        boolean flag = false;
        String s = txt.getText();
        for(int i=0;i<s.length();i++){
            if('0'<=s.charAt(i)&&s.charAt(i)<='9'){
                flag=true;
            }else{
                flag= false;
            }
        }
        return flag;
    }
    
    public void sales(){
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd");
        LocalDateTime now = LocalDateTime.now();
        String date = dtf.format(now);
        String subTotal = txtTotalCost.getText();
        String pay = txtPay.getText();
        String balance = txtBalance.getText();
        int lastInsertedId = 0;
        try {
            String sql = "insert into sales(date,subtotal,pay,balance) values(?,?,?,?)";
            pst = con.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
            pst.setString(1, date);
            pst.setString(2, subTotal);
            pst.setString(3, pay);
            pst.setString(4, balance);
            
            int count = pst.executeUpdate();
            rs = pst.getGeneratedKeys();
            if(count>0){
                if(rs.next()){
                    lastInsertedId = rs.getInt(1);
                } 
                int rows = jtbleDrug.getColumnCount();
                String sql1 = "insert into sale_product(sales_id,pro_id,sellprice,qty,total) values(?,?,?,?,?)";
                
                pst = con.prepareStatement(sql1);
                
            
                for(int i=0;i<jtbleDrug.getRowCount();i++){
                    String pres_id = (String)jtbleDrug.getValueAt(i, 0);
                    String item_id = (String)jtbleDrug.getValueAt(i, 1);
                    String qty = jtbleDrug.getValueAt(i, 3).toString();
                    int qty1 = Integer.parseInt(qty);
                    int price = (int)jtbleDrug.getValueAt(i, 4);
                    int total = (int)jtbleDrug.getValueAt(i, 5);
                    pst.setInt(1, lastInsertedId);
                    pst.setString(2, item_id);
                    pst.setInt(3, price);
                    pst.setInt(4, qty1);
                    pst.setInt(5, total);
                    int updated = pst.executeUpdate();
                    if(updated>0){
                        
                        }else{
                        JOptionPane.showMessageDialog(this, "Wrong input");
                        break;
                    }
                    
                }
                String updateItems = "Update items set qty =qty-? where itemno =?";
                pst = con.prepareStatement(updateItems);
                for(int i=0;i<jtbleDrug.getRowCount();i++){
                    String item_id = (String)jtbleDrug.getValueAt(i, 1);
                    String qty = jtbleDrug.getValueAt(i, 3).toString();
                    int qty1 = Integer.parseInt(qty);
                    pst.setInt(1, qty1);
                    pst.setString(2, item_id);
                    int updated = pst.executeUpdate();
                    if(updated>0){
                        JOptionPane.showMessageDialog(this, "Record Added...");
                        txtDrugName.setText("");
                        txtTotalCost.setText("");
                        txtPay.setText("");
                        txtBalance.setText("");
                        txtDrugCode.requestFocus();
                        btnadd.setEnabled(false);
                        btnSalesUpdate.setEnabled(false);
                        btnClear.setEnabled(false);
                    }else{
                        JOptionPane.showMessageDialog(this, "Wrong input");
                        break;
                    }
                }
                
            }else{
                 JOptionPane.showMessageDialog(this, "Wrong input");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Inventory.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        
    }
    
    private void btnSalesUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesUpdateActionPerformed
        if(numCheck(txtPay)){
        int pay = Integer.parseInt(txtPay.getText());
        int totalCost = Integer.parseInt(txtTotalCost.getText());
        int bal = pay - totalCost;
        if(totalCost<=pay){
        txtBalance.setText(String.valueOf(bal));
        sales(); 
        btnClear.setEnabled(true);
        }else {
            JOptionPane.showMessageDialog(this, "Payment Money: "+pay+"\nNeed Amount:"+totalCost+"\nInsufficent money");
            txtBalance.setText(String.valueOf(bal));
            txtPay.requestFocus();
        }
    }
    }//GEN-LAST:event_btnSalesUpdateActionPerformed

    private void txtQtyCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtQtyCaretPositionChanged

    }//GEN-LAST:event_txtQtyCaretPositionChanged

    private void txtQtyInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtQtyInputMethodTextChanged

    }//GEN-LAST:event_txtQtyInputMethodTextChanged

    private void btnlogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlogoutActionPerformed
        System.gc();
        this.setVisible(false);
        new MainPharmacist(this.id,this.username,this.usertype,con).setVisible(true);
    }//GEN-LAST:event_btnlogoutActionPerformed

    private void jtbleDrugMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbleDrugMouseClicked

    }//GEN-LAST:event_jtbleDrugMouseClicked

    private void jtbleDrugMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbleDrugMousePressed

    }//GEN-LAST:event_jtbleDrugMousePressed

    private void txtQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyFocusLost

    }//GEN-LAST:event_txtQtyFocusLost

    private void txtQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyFocusGained
       
    }//GEN-LAST:event_txtQtyFocusGained

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
                        txtDrugCode.setSelectedIndex(0);
                        txtDrugName.setText("");
                        txtQty.setValue(0);
                        txtTotalCost.setText("");
                        txtPay.setText("");
                        txtPay.setEditable(false);
                        txtBalance.setText("");
                        txtDrugCode.requestFocus();
                        jChkDrugCode.setSelected(false);
    }//GEN-LAST:event_btnClearActionPerformed

    private void txtTotalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalCostActionPerformed

    private void txtDrugCodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDrugCodeFocusLost
        if(!txtDrugCode.getSelectedItem().toString().equals("")||!txtDrugCode.getSelectedItem().equals(null)){
            
        }else{
            JOptionPane.showMessageDialog(this,"Please fill Drug Code");
            txtDrugCode.requestFocus();
        }
    }//GEN-LAST:event_txtDrugCodeFocusLost

    private void jChkDrugCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkDrugCodeActionPerformed
        if(jChkDrugCode.isSelected()){
            DrugCheckput();
            btnadd.setEnabled(true);
            
        }else{
            btnadd.setEnabled(false);
        }
    }//GEN-LAST:event_jChkDrugCodeActionPerformed

    private void txtDrugCodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDrugCodeFocusGained
        jChkDrugCode.setSelected(false);
    }//GEN-LAST:event_txtDrugCodeFocusGained

    private void txtBalanceFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBalanceFocusLost
      
    }//GEN-LAST:event_txtBalanceFocusLost

    private void txtPayFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPayFocusLost
       if(numCheck(txtPay)){
           btnSalesUpdate.setEnabled(true);
       }
    }//GEN-LAST:event_txtPayFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inventory().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSalesUpdate;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnlogout;
    private javax.swing.JCheckBox jChkDrugCode;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbleDrug;
    private javax.swing.JLabel lblPno;
    private javax.swing.JLabel lbllogid;
    private javax.swing.JLabel lblusername;
    private javax.swing.JTextField txtBalance;
    private javax.swing.JComboBox<String> txtDrugCode;
    private javax.swing.JTextField txtDrugName;
    private javax.swing.JTextField txtPay;
    private javax.swing.JSpinner txtQty;
    private javax.swing.JTextField txtTotalCost;
    // End of variables declaration//GEN-END:variables
}
